### ISSUE TITLE
Chrome Web Store link for shipscope returns 404s

### ISSUE THREAD

**Issue by soultech67** [codeship/shipscope#29]
Trying to get my team to use this tool, but it is now returning 404s for shipscope in the webstore https://chrome.google.com/webstore/detail/shipscope/jdedmgopefelimgjceagffkeeiknclhh?hl=en

**Comment by jschley** [comment]
Sorry for the inconvenience and thank you for opening the issue here. I opened a PR to update the link in the Readme: https://github.com/codeship/shipscope/pull/30
The proper URL to the Chrome webstore is https://github.com/codeship/shipscope/pull/30/files
